---
title: "STA313 Final Project- Mock"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

source("app/init.R")

library(tidyverse)
library(lubridate)

fire_incidents <- read.csv("app/data/Fire_Incidents.csv", header=T, stringsAsFactors = T)   

```


```{r fire_incidents}

# remove extreme cases
fire_incidents <- fire_incidents %>% filter(Estimated_Dollar_Loss < 1000000 & Number_of_responding_personnel != 1275) %>%
  filter(Area_of_Origin != "" & Status_of_Fire_On_Arrival != "" & !is.na(Status_of_Fire_On_Arrival))

## Status of fire on arrival
fire_incidents <- fire_incidents %>% mutate(Fire_Size_Case = case_when(
  Status_of_Fire_On_Arrival == "1 - Fire extinguished prior to arrival" ~ fire_Size_Table[1],
  Status_of_Fire_On_Arrival == "2 - Fire with no evidence from street" ~ fire_Size_Table[2],
  Status_of_Fire_On_Arrival == "3 - Fire with smoke showing only - including vehicle, outdoor fires" ~ fire_Size_Table[3],
  Status_of_Fire_On_Arrival == "4 - Flames showing from small area (one storey or less, part of a vehicle, outdoor)" ~ fire_Size_Table[3],
  Status_of_Fire_On_Arrival == "5 - Flames showing from large area (more than one storey, large area outdoors)" ~ fire_Size_Table[4],
  Status_of_Fire_On_Arrival == "7 - Fully involved (total structure, vehicle, spreading outdoor fire)" ~ fire_Size_Table[4],
  Status_of_Fire_On_Arrival == "8 - Exposure involved" ~ fire_Size_Table[4],
  Status_of_Fire_On_Arrival == "9 - Unclassified" ~ fire_Size_Table[5],
)) %>% mutate(Fire_Size_Case = factor(Fire_Size_Case, levels = fire_Size_Table))

## Type of fire on arrival
fire_incidents <- fire_incidents %>% mutate(Fire_Type_Case = case_when(
  Final_Incident_Type == "01 - Fire" ~ fire_Type_Table[1],
  Final_Incident_Type == "02 - Explosion (including during Fire, excluding Codes 3 & 11-13)" ~ fire_Type_Table[2]
)) %>% mutate(Fire_Type_Case = factor(Fire_Type_Case, levels = fire_Type_Table))

## Type of fire on arrival
fire_incidents <- fire_incidents %>% mutate(Area_Orgin_Case = case_when(
  Area_of_Origin == "24 - Cooking Area or Kitchen" ~ area_Origin_Table[1],
  Area_of_Origin == "44 - Trash, Rubbish Storage (inc garbage chute room, garbage/industri" ~ area_Origin_Table[2],
  Area_of_Origin == "64 - Porch or Balcony" ~ area_Origin_Table[3],
  Area_of_Origin == "81 - Engine Area" ~ area_Origin_Table[4],
  TRUE ~ area_Origin_Table[5]
)) %>% mutate(Area_Orgin_Case = factor(Area_Orgin_Case, levels = area_Origin_Table))

# Read map and dots of interest
map <- readRDS("app/data/neighbourhood_shapefile.Rds")
pntf <- data.frame(X = fire_incidents$Latitude, Y = fire_incidents$Longitude,
                     X_id = fire_incidents$X_id) %>% na.omit() 
  
pnts_sf <- sf::st_as_sf(pntf, coords = c('Y', 'X'), crs = sf::st_crs(map))
  
pnts <- pnts_sf %>% dplyr::mutate(
    intersection = as.integer(sf::st_intersects(pnts_sf$geometry, map))
    , Neighborhood = if_else(is.na(intersection), '', map$AREA_NAME[intersection])
) 
  
fire_incidents <- left_join(fire_incidents, pnts, by="X_id") %>% filter(!is.na(Neighborhood)) %>% 
  filter(Neighborhood != "")

# date transformation
TFS_Arrival_Time <- gsub("T", " ", fire_incidents$TFS_Arrival_Time) %>% as.POSIXct(format='%Y-%m-%d %H:%M:%OS')
TFS_Alarm_Time <- gsub("T", " ", fire_incidents$TFS_Alarm_Time) %>% as.POSIXct(format='%Y-%m-%d %H:%M:%OS')

fire_incidents$TFS_Response_Time <- difftime(TFS_Arrival_Time, TFS_Alarm_Time, units = "min") %>% as.numeric()

# date manipulation
fire_incidents$TFS_Alarm_Date <- gsub("T.*$", "", fire_incidents$TFS_Alarm_Time) %>% as.Date()
fire_incidents$TFS_Alarm_Time <- gsub(".*T", "", fire_incidents$TFS_Alarm_Time) 
fire_incidents$TFS_Alarm_Month <- floor_date(fire_incidents$TFS_Alarm_Date, "month")
fire_incidents$TFS_Alarm_Year <- floor_date(fire_incidents$TFS_Alarm_Date, "year")

# save as RDS for quicker access
saveRDS(fire_incidents, "app/data/Cleaned_Fire_Incidents.Rds")

```

```{r fire_incidents_trim}

remain <- c("X_id","Area_of_Origin","Neighborhood", "Intersection","geometry", "TFS_Alarm_Year", "TFS_Alarm_Month", 
            "TFS_Alarm_Date", "TFS_Response_Time", "Area_Orgin_Case", "Fire_Type_Case", "Fire_Size_Case",
            "Status_of_Fire_On_Arrival", "Final_Incident_Type",
            "Number_of_responding_personnel", "Estimated_Dollar_Loss",
            "Latitude", "Longitude", "Civilian_Casualties")

fire_incidents_trimmed <- fire_incidents[, names(fire_incidents) %in% remain]

saveRDS(fire_incidents_trimmed, "app/data/Trimmed_Fire_Incidents.Rds")

```

```{r fire_station}

fireStation <- read.csv("app/data/Fire_Station_Locations.csv", header = T)

# Read map and dots of interest
map <- readRDS("app/data/neighbourhood_shapefile.Rds")
pntf <- data.frame(X = fireStation$Latitude, Y = fireStation$Longitude,
                     ID = fireStation$ID) %>% na.omit() 
  
pnts_sf <- sf::st_as_sf(pntf, coords = c('Y', 'X'), crs = sf::st_crs(map))
  
pnts <- pnts_sf %>% dplyr::mutate(
    intersection = as.integer(sf::st_intersects(pnts_sf$geometry, map))
    , Neighborhood = if_else(is.na(intersection), '', map$AREA_NAME[intersection])
) 
  
fireStation <- left_join(fireStation, pnts, by="ID") %>% filter(!is.na(Neighborhood)) %>% 
  filter(Neighborhood != "")

# Trim fire station data
fireStation <- fireStation[,-which(names(fireStation) %in% c("geometry", "intersection"))]

saveRDS(fireStation, "app/data/Trimmed_Fire_Station.Rds")

```

```{r neighbourhood}

neighbourhood_Shape <- readRDS("app/data/neighbourhood_shapefile.Rds")
population <- read.csv("app/data/Neighbourhood_Profiles.csv", 
                       header = T, stringsAsFactors = F,
                       colClasses=rep("numeric", 14))

# Get total incidents
fire_incidents_summary <- fire_incidents_trimmed %>% group_by(Neighborhood) %>%
  summarise(Total_Incidents = n(), Average_Response_Time = round(mean(TFS_Response_Time), 2), Average_Casualty = round(mean(Civilian_Casualties),2), Average_Financial_Loss = round(mean(Estimated_Dollar_Loss),2))

neighbourhoods <- merge(neighbourhood_Shape, fire_incidents_summary, by.x = "AREA_NAME", by.y="Neighborhood")

# Get total fire stations
fire_station_summary <- fireStation %>% group_by(Neighborhood) %>%
  summarise(Total_Station = n())

neighbourhoods <- left_join(neighbourhoods, fire_station_summary, by = c("AREA_NAME" = "Neighborhood"))
neighbourhoods[which(is.na(neighbourhoods$Total_Station)),]$Total_Station <- 0

# Get population 
neighbourhoods$Area_Short_Code <- as.numeric(neighbourhoods$AREA_SHORT_CODE)
neighbourhoods <- merge(neighbourhoods, population, by = "Area_Short_Code")

neighbourhoods <- neighbourhoods[,-which(names(neighbourhoods) %in% c("PARENT_AREA_ID", "_id", "X", "AREA_DESC", "AREA_SHORT_CODE",
                                                                      "Y", "LONGITUDE", "LATITUDE", "AREA_LONG_CODE", 
                                                                      "AREA_ATTR_ID", "CLASSIFICATION_CODE", "CLASSIFICATION"
                                                                      ))] %>% na.omit()
names(neighbourhoods)[2] <- "Area_Name"

saveRDS(neighbourhoods, "app/data/neighbourhoods_info.Rds")

```