---
title: "STA313_map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

if (!requireNamespace("sf", quietly = TRUE))    
    install.packages("sf")
if (!requireNamespace("raster", quietly = TRUE))    
    install.packages("raster")
if (!requireNamespace("dplyr", quietly = TRUE))    
    install.packages("dplyr")
if (!requireNamespace("spData", quietly = TRUE))    
    install.packages("spData")
if (!requireNamespace("tidyverse", quietly = TRUE))    
    install.packages("tidyverse")
if (!requireNamespace("lubridate", quietly = TRUE))    
    install.packages("lubridate")
if (!requireNamespace("tmap", quietly = TRUE))    
    install.packages("tmap")
if (!requireNamespace("leaflet", quietly = TRUE))    
    install.packages("leaflet")
if (!requireNamespace("ggplot2", quietly = TRUE))    
    install.packages("ggplot2")

library(dplyr)
```

## Including Plots

You can also embed plots, for example:

```{r add_area, echo=FALSE}

if (!file.exists("Fire_Incidents.Rds")){
  
  # Read map and dots of interest
  map <- readRDS("data/neighbourhood_shapefile.Rds")
  fireIncidents <- read.csv("data/Fire_Incidents.csv", header=T, stringsAsFactors = T)
  pntf <- data.frame(X = fireIncidents$Latitude, Y = fireIncidents$Longitude,
                     X_id = fireIncidents$X_id) %>% na.omit()
  
  pnts_sf <- sf::st_as_sf(pntf, coords = c('Y', 'X'), crs = sf::st_crs(map))
  
  pnts <- pnts_sf %>% dplyr::mutate(
    intersection = as.integer(sf::st_intersects(pnts_sf$geometry, map))
    , AREA_NAME = if_else(is.na(intersection), '', map$AREA_NAME[intersection])
  ) 
  
  fireIncidents <- left_join(fireIncidents, pnts, by="X_id")
  
  # save as RDS for quicker access
  saveRDS(fireIncidents, "data/Fire_Incidents.Rds")
  
} 

fireIncidents <- readRDS("data/Fire_Incidents.Rds")
```

```{r map}


fireIncidentsCounts <- pnts %>% as.data.frame %>% dplyr::group_by(AREA_NAME) %>% dplyr::summarise(count=n()) %>% subset(AREA_NAME != "")
fireIncidentsCountsByRegion <- left_join(fireIncidentsCounts, map, by="AREA_NAME") 

tmap::tmap_mode("view")

tmap::tm_shape(sf::st_as_sf(fireIncidentsCountsByRegion)) + 
  tmap::tm_polygons("count",palette = "BuGn")+
  tmap::tm_borders(lwd = 0.5, lty = 0.1) + 
  tmap::tm_scale_bar(breaks = c(0, 2, 4), text.size = 1) +   
  tmap::tm_shape(pnts) + tmap::tm_dots(border.col = NA, size = 0.005, clustering = F)
```
